apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc1-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc1-frontend
  template:
    metadata:
      labels:
        app: doc1-frontend
    spec:
      containers:
      - name: doc1-frontend
        image: totlevi/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          value: " http://127.0.0.1:59365"

---
apiVersion: v1
kind: Service
metadata:
  name: doc1-frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: doc1-frontend
