name: CD - Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest
    name: Push images to Docker Hub
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            totlevi/backend
            totlevi/frontend

      - name: Build and push backend image
        id: push_backend
        uses: docker/build-push-action@v4
        with:
          context: ./Spring
          file: ./Spring/Dockerfile
          push: true
          tags: totlevi/backend:latest, totlevi/backend:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push frontend image
        id: push_frontend
        uses: docker/build-push-action@v4
        with:
          context: ./React
          file: ./React/Dockerfile
          push: true
          tags: totlevi/frontend:latest, totlevi/frontend:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-minikube:
    runs-on: ubuntu-latest
    name: Deploy to Minikube
    needs: push-to-docker-hub
    steps:
      - uses: actions/checkout@v4
      
      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Verify cluster
        run: kubectl get pods -A

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Deploy to Minikube
        run: |
          cd deployments
          kubectl apply -f deployment-backend.yaml
          kubectl apply -f deployment-frontend.yaml
      
      - name: Test service URLs
        run: minikube service list

